codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,footer"
  behavior: default
  require_changes: true  # Only post the comment if coverage changes
  require_base: yes        # Must have a base report to post
  require_head: yes       # Must have a head report to post
