plugins {
    id 'com.diffplug.spotless' version '8.10.0'
    id 'groovy'
    id 'java'
    id 'java-gradle-plugin'
    id 'jvm-test-suite'
    id 'maven-publish'
    id 'net.ltgt.errorprone' version '5.1.0'
}

java {
    toolchain {
      languageVersion.set(JavaLanguageVersion.of(17))
    }
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

group = 'se.kth.castor'
version = '2.2.0-SNAPSHOT'

repositories {
  mavenLocal()
  mavenCentral()
}

ext {
    depcleanVersion = '2.2.0-SNAPSHOT'
    errorProneCoreVersion = '2.50.0'
    jspecifyVersion = '1.0.1'
    lombokVersion = '1.18.46'
    nullawayVersion = '0.14.0'
    slf4jVersion = '2.0.18'
    spockVersion = '2.4-groovy-4.0'
    spotbugsAnnotationsVersion = '4.10.4'
}

dependencies {
    implementation(gradleApi())
    implementation(gradleTestKit())
    implementation("se.kth.castor:depclean-core:${depcleanVersion}")
    implementation("se.kth.castor:depclean-maven-plugin:${depcleanVersion}")
    implementation("org.slf4j:slf4j-reload4j:${slf4jVersion}")
    compileOnly("org.jspecify:jspecify:${jspecifyVersion}")

    compileOnly("org.projectlombok:lombok:${lombokVersion}")
    annotationProcessor("org.projectlombok:lombok:${lombokVersion}")
    implementation("com.github.spotbugs:spotbugs-annotations:${spotbugsAnnotationsVersion}")

    testImplementation("org.spockframework:spock-core:${spockVersion}")

    errorprone("com.google.errorprone:error_prone_core:${errorProneCoreVersion}")
    compileOnly("com.google.errorprone:error_prone_annotations:${errorProneCoreVersion}")
    annotationProcessor("com.uber.nullaway:nullaway:${nullawayVersion}")
}

testing {
    suites {
        test {
            useSpock()
        }
    }
}

spotless {
  java {
    googleJavaFormat()
  }
}

gradlePlugin {
    plugins {
        depcleanPlugin {
            id = 'se.kth.castor.depclean-gradle-plugin'
            implementationClass = 'se.kth.depclean.DepCleanGradlePlugin'
            displayName = 'DepClean Gradle Plugin'
            description = 'A plugin to analyze and debloat dependencies in Gradle projects'
        }
    }
}

import net.ltgt.gradle.errorprone.CheckSeverity

tasks.withType(JavaCompile).configureEach {
    options.errorprone {
        check("NullAway", CheckSeverity.ERROR)
        option("NullAway:AnnotatedPackages", "se.kth.depclean")
    }
}

// Reproducible archives
tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}
