name: Deploy
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true
jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: 17
          server-id: ossrh
          server-username: ${{ secrets.NEXUS_USERNAME }}
          server-password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Deploy Maven package
        run: mvn deploy -P deploy
        env:
          MAVEN_USERNAME: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_PASSWORD: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create and push tag
        run: |
          git config --global user.email "cesarsotovalero@gmail.com"
          git config --global user.name "$GITHUB_ACTOR"
          git tag -a $TAG -m "Release v$TAG"
          git push origin $TAG
        env:
          TAG: ${{ github.event.inputs.versionName }}

      - name: Create Release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.versionName }}
          release_name: MyLib ${{ github.event.inputs.versionName }}
          draft: true
          prerelease: false