name: Master Branch Workflow

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:

  #  Compile and package the Maven project.
  package:
    name: Package - Generate JARs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8, 11 ]
        os: [ [ ubuntu-latest, windows-latest ] ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Maven Package
        run: mvn -B clean package -DskipTests

  # Runs unit tests (via surefire-maven-plugin) and integration tests (via failsafe-maven-plugin).
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: mvn clean verify --batch-mode --fail-at-end
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

  # Collect JaCoCo test coverage and report to Coveralls
  coveralls:
    name: Report - Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: mvn clean test
      - name: Report to Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Run SonarCloud static analysis.
  sonar:
    name: Scan - SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: SonarCloud Scan
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish the JAR artifacts to GitHub Packages.
  publish:
    name: Publish - GitHub Packages
    runs-on: ubuntu-latest
    needs: [ package, test, sonar ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish Artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
